rework: rebase to linuxserver.io baseimage
use modern s6 init structure, use linuxserver.io default user `abc`

diff --git a/root/etc/s6-overlay/s6-rc.d/init-websvn/run b/root/etc/s6-overlay/s6-rc.d/init-websvn/run
--- a/root/etc/s6-overlay/s6-rc.d/init-websvn/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-websvn/run
@@ -11,30 +11,30 @@ WEBSVN_URL=$(echo "$WEBSVN_URL" | sed 's_/$__g')
 
 # early out if WEBSVN_URL is not configured
 if [ -z "${WEBSVN_URL}" ]; then
-    echo "Info: Disable WebSVN as WEBSVN_URL is empty"
-    exit 0
+  echo "Info: Disable WebSVN as WEBSVN_URL is empty"
+  exit 0
 fi
 
 case $(int ${WEBSVN_AUTH}) in
 0 | 1 | 2)
-    # valid values, nothing todo
-    ;;
+  # valid values, nothing todo
+  ;;
 *)
-    echo "Error: invalid value WEBSVN_AUTH='${WEBSVN_AUTH}'"
-    echo "Info: disable WebSVN"
-    exit 1
-    ;;
+  echo "Error: invalid value WEBSVN_AUTH='${WEBSVN_AUTH}'"
+  echo "Info: disable WebSVN"
+  exit 1
+  ;;
 esac
 
 # ensure it starts with a slash
 echo "${WEBSVN_URL}" | grep ^/ > /dev/null
 if [ ${?} != 0 ]; then
-    WEBSVN_URL="/${WEBSVN_URL}"
+  WEBSVN_URL="/${WEBSVN_URL}"
 fi
 
 # /data/websvn: persistent storage for websvn configuration
 if [ ! -d /data/websvn ]; then
-    mkdir -p /data/websvn
+  install -d -o abc -g abc /data/websvn
 fi
 
 # enable apache authentification IF WEBSVN_AUTH >= 1
@@ -51,19 +51,17 @@ fi
 
 # create link in htdocs
 if [ ! -e /var/www/localhost/htdocs${WEBSVN_URL} ]; then
-    ln -s /opt/websvn /var/www/localhost/htdocs${WEBSVN_URL}
+  ln -s /opt/websvn /var/www/localhost/htdocs${WEBSVN_URL}
 fi
 
 # copy configuration template
-cp /opt/websvn/include/distconfig.php /data/websvn/distconfig.php
+install -o abc -g abc /opt/websvn/include/distconfig.php /data/websvn/distconfig.php
 
 # copy default configuration if not yet existing e.g. initial start
 if [ ! -f /data/websvn/config.php ]; then
-    cp /opt/default_data/websvn/config.php /data/websvn/config.php
+  install -o abc -g abc /opt/default_data/websvn/config.php /data/websvn/config.php
 fi
 
 # force update of config.php link 
 rm -f /opt/websvn/include/config.php
 ln -s /data/websvn/config.php /opt/websvn/include/config.php
-
-chown -R svn:svnusers /data/websvn
